/**
 * lib/stockReport.js
 * Pure aggregation for the Distributor Stock & Sales module. No DB calls — mirrors
 * achievementEngine.js's shape (fed pre-loaded arrays, returns computed rows).
 *
 * Two independent computations live here, and they must stay independent:
 *
 * `computeStockLedger` — the Stock & Sales Report itself (Summary/Detail tabs). Has NOTHING to do
 * with physical stock-take dates; it's a plain running ledger over a user-chosen [from, to] date
 * range, same convention as every other date-ranged report in this app (DistributorSecondaryReport,
 * etc.). Opening = the one-time approved Opening Stock baseline plus every Receipt/Sale dated before
 * `from`; Receipts/Sales = real transactions dated within [from, to]; Closing is always the
 * calculated figure (Opening + Receipts − Sales), never a physical count — this report doesn't touch
 * physical counts at all.
 *
 * `computeStockTakePeriods` — feeds ONLY the Discrepancy Report (generated by StockTakeEntry.jsx
 * right after a physical count is saved). This one IS anchored to stock-take dates on purpose: each
 * physical stock take chops that distributor's timeline into a take-to-take period, and this is what
 * lets a Discrepancy Report compare the ledger's Calculated Closing against the real Physical Closing
 * at the exact moment a count happened. The Stock & Sales Report must never call this function, and
 * this function must never be shown a manually-picked date range — conflating the two is the mistake
 * this file's history keeps correcting.
 *
 * Every quantity figure also carries a parallel *Value figure (currency). Receipts/Sales value comes
 * from the real per-line transaction rate (already on the invoice line / order item — an actual price
 * something changed hands at). Opening/Closing have no transaction of their own (point-in-time
 * balances, not events) — those are valued off the product's master price instead, passed in via
 * `products`.
 */

import { localDateStr } from './period.js'

export const round1 = n => (n === null || n === undefined ? null : Math.round((Number(n) || 0) * 10) / 10)

// ─── shared prep: flatten raw fetch rows into per-distributor qty+value event lists ───────────────

function priceMap(products) {
  const m = {}
  products.forEach(p => { m[p.id] = Number(p.price) || 0 })
  return m
}

// invoices: fetchReceiptsForStockReport() rows (approved invoices, each with `lines` + embedded
// `order.delivered_at`). An order-linked invoice only counts once the driver has actually confirmed
// delivery; a legacy/manual invoice (no order_id) has nothing to confirm, so it counts outright.
function flattenReceipts(invoices) {
  const byDistributor = {}
  invoices.forEach(inv => {
    if (inv.order_id && !inv.order?.delivered_at) return
    const date = inv.order?.delivered_at ? localDateStr(new Date(inv.order.delivered_at)) : localDateStr(new Date(inv.date))
    ;(inv.lines || []).forEach(l => {
      if (!byDistributor[inv.distributor_id]) byDistributor[inv.distributor_id] = []
      const qty = Number(l.qty) || 0
      byDistributor[inv.distributor_id].push({ productId: l.product_id, qty, value: qty * (Number(l.rate) || 0), date })
    })
  })
  return byDistributor
}

// secondaryOrders: fetchDeliveredSecondaryOrdersForStockReport() rows (each with `items` + embedded
// `delivery.marked_at`/`delivery.delivery_items`). Sale qty is delivered qty (ordered minus any
// returned qty from a partial delivery), dated to when the delivery outcome was actually marked.
function flattenSales(secondaryOrders) {
  const byDistributor = {}
  secondaryOrders.forEach(o => {
    if (!o.delivery?.delivered_date) return
    // delivered_date is a plain `date` column (rep-entered, defaults to today but editable — see
    // SecondaryOrderDelivery.jsx), already a bare 'YYYY-MM-DD' with no timezone component, unlike
    // marked_at (a timestamptz audit stamp of when the app action happened, never used for dating a
    // Sale — see this file's own header comment on why Sales must reflect the real delivery date).
    const date = o.delivery.delivered_date
    const returnedByItem = {}
    ;(o.delivery.delivery_items || []).forEach(di => { returnedByItem[di.order_item_id] = Number(di.returned_qty) || 0 })
    ;(o.items || []).forEach(it => {
      const delivered = Math.max(0, (Number(it.qty) || 0) - (returnedByItem[it.id] || 0))
      if (!byDistributor[o.distributor_id]) byDistributor[o.distributor_id] = []
      byDistributor[o.distributor_id].push({ productId: it.product_id, qty: delivered, value: delivered * (Number(it.rate) || 0), date })
    })
  })
  return byDistributor
}

// openingStocks: fetchOpeningStocks() rows (each with `items`; only `status === 'approved'` used).
function flattenOpeningBaseline(openingStocks) {
  const byKey = {} // `${distributorId}|${productId}` -> one-time baseline qty
  openingStocks.forEach(os => {
    if (os.status !== 'approved') return
    ;(os.items || []).forEach(it => { byKey[`${os.distributor_id}|${it.product_id}`] = Number(it.qty) || 0 })
  })
  return byKey
}

function sumWhere(bucket, distributorId, productId, predicate) {
  const matches = (bucket[distributorId] || []).filter(d => d.productId === productId && predicate(d.date))
  return { qty: matches.reduce((s, d) => s + d.qty, 0), value: matches.reduce((s, d) => s + d.value, 0) }
}

// ─── Stock & Sales Report — plain date-range ledger, no stock-take dependency ──────────────────────

// invoices/secondaryOrders/openingStocks/products: see file header. distributorIds: distributors in
// scope. productIds: optional explicit product filter — when omitted, every product that has ever
// had an approved opening baseline or a real receipt/sale for that distributor is included (not a
// full distributor×product cross-product — that would be mostly empty rows for anything real-sized).
// from/to: 'YYYY-MM-DD' strings, inclusive on both ends, user-chosen (no relationship to stock takes).
export function computeStockLedger({
  invoices = [], secondaryOrders = [], openingStocks = [], products = [],
  distributorIds = [], productIds = null, from, to,
}) {
  const price = priceMap(products)
  const productMeta = {}
  products.forEach(p => { productMeta[p.id] = p })
  const receiptsByDistributor = flattenReceipts(invoices)
  const salesByDistributor = flattenSales(secondaryOrders)
  const openingBaseline = flattenOpeningBaseline(openingStocks)

  const summary = []
  const detail = []

  distributorIds.forEach(distributorId => {
    // Scope products to whichever ones actually have SOME history for this distributor (an approved
    // baseline, or at least one receipt/sale ever) — not every product in the catalog, which would
    // mostly be irrelevant empty rows.
    const everProducts = new Set([
      ...Object.keys(openingBaseline).filter(k => k.startsWith(`${distributorId}|`)).map(k => k.split('|')[1]),
      ...(receiptsByDistributor[distributorId] || []).map(d => d.productId),
      ...(salesByDistributor[distributorId] || []).map(d => d.productId),
    ])
    const scopeProducts = productIds ? productIds.filter(id => everProducts.has(id)) : Array.from(everProducts)

    scopeProducts.forEach(productId => {
      const p = price[productId] || 0
      const baseline = openingBaseline[`${distributorId}|${productId}`] ?? 0
      const priorReceipts = sumWhere(receiptsByDistributor, distributorId, productId, d => d < from)
      const priorSales = sumWhere(salesByDistributor, distributorId, productId, d => d < from)
      const opening = baseline + priorReceipts.qty - priorSales.qty

      const receipts = sumWhere(receiptsByDistributor, distributorId, productId, d => d >= from && d <= to)
      const sales = sumWhere(salesByDistributor, distributorId, productId, d => d >= from && d <= to)
      const closing = opening + receipts.qty - sales.qty

      summary.push({
        distributorId, productId, productName: productMeta[productId]?.name || productId, unit: productMeta[productId]?.unit,
        from, to,
        opening, openingValue: opening * p,
        receipts: receipts.qty, receiptsValue: receipts.value,
        sales: sales.qty, salesValue: sales.value,
        closing, closingValue: closing * p,
      })

      ;(receiptsByDistributor[distributorId] || [])
        .filter(d => d.productId === productId && d.date >= from && d.date <= to)
        .forEach(d => detail.push({
          distributorId, productId, productName: productMeta[productId]?.name || productId, unit: productMeta[productId]?.unit,
          date: d.date, type: 'Receipt', qty: d.qty, value: d.value,
        }))
      ;(salesByDistributor[distributorId] || [])
        .filter(d => d.productId === productId && d.date >= from && d.date <= to)
        .forEach(d => detail.push({
          distributorId, productId, productName: productMeta[productId]?.name || productId, unit: productMeta[productId]?.unit,
          date: d.date, type: 'Sale', qty: d.qty, value: d.value,
        }))
    })
  })

  detail.sort((a, b) => new Date(b.date) - new Date(a.date))
  return { summary, detail }
}

// ─── Discrepancy Report source — anchored to real stock-take dates, unrelated to the ledger above ──

// stockTakes: fetchStockTakesForDistributors() rows (take_date-ascending, each with `items`). Same
// invoices/secondaryOrders/openingStocks/products/distributorIds/productIds shape as above. Used
// exclusively by StockTakeEntry.jsx right after a physical count saves — never by the Stock & Sales
// Report page.
export function computeStockTakePeriods({
  stockTakes = [], invoices = [], secondaryOrders = [], openingStocks = [], products = [],
  distributorIds = [], productIds = null,
}) {
  const periods = [] // flat list, one row per (distributor, product, period) — Discrepancy Report source
  const latestByKey = {}

  const price = priceMap(products)
  const receiptsByDistributor = flattenReceipts(invoices)
  const salesByDistributor = flattenSales(secondaryOrders)
  const approvedOpeningByKey = flattenOpeningBaseline(openingStocks)

  const takesByDistributor = {}
  stockTakes.forEach(t => {
    if (!takesByDistributor[t.distributor_id]) takesByDistributor[t.distributor_id] = []
    takesByDistributor[t.distributor_id].push(t)
  })

  const sumFor = (bucket, distributorId, productId, fromExclusive, toInclusive) =>
    sumWhere(bucket, distributorId, productId, d => d <= toInclusive && (fromExclusive === null || d > fromExclusive))

  distributorIds.forEach(distributorId => {
    const takes = takesByDistributor[distributorId] || []
    if (takes.length === 0) return

    const scopeProducts = productIds || Array.from(new Set(takes.flatMap(t => (t.items || []).map(it => it.product_id))))

    scopeProducts.forEach(productId => {
      let lastKnownClosing = null // carries the last real physical count forward across a take that skipped this product
      let productMeta = null
      const p = price[productId] || 0

      takes.forEach((take, i) => {
        const item = (take.items || []).find(it => it.product_id === productId)
        if (item?.product && !productMeta) productMeta = item.product

        const from = i === 0 ? null : takes[i - 1].take_date
        const to = take.take_date
        const opening = i === 0 ? (approvedOpeningByKey[`${distributorId}|${productId}`] ?? 0) : lastKnownClosing
        const receipts = sumFor(receiptsByDistributor, distributorId, productId, from, to)
        const sales = sumFor(salesByDistributor, distributorId, productId, from, to)
        const closing = item ? Number(item.physical_qty) || 0 : null // physical count, ground truth — never calculated
        const calculatedClosing = opening === null ? null : opening + receipts.qty - sales.qty
        const variance = (closing === null || calculatedClosing === null) ? null : round1(closing - calculatedClosing)

        // takeId (not just `to`, a date string) is what a caller needs to identify "the period THIS
        // specific stock take produced" — two takes for the same distributor can land on the same
        // calendar date (a same-day recount, or a voluntary count landing the same day as a forced
        // one), and matching on date string alone would ambiguously pick up both.
        const period = {
          distributorId, productId, productName: productMeta?.name || productId, unit: productMeta?.unit,
          from, to, takeId: take.id,
          opening, openingValue: opening === null ? null : opening * p,
          receipts: receipts.qty, receiptsValue: receipts.value,
          sales: sales.qty, salesValue: sales.value,
          closing, closingValue: closing === null ? null : closing * p,
          calculatedClosing, calculatedClosingValue: calculatedClosing === null ? null : calculatedClosing * p,
          variance, varianceValue: variance === null ? null : round1(variance * p),
        }
        periods.push(period)
        if (closing !== null) lastKnownClosing = closing
        latestByKey[`${distributorId}|${productId}`] = period
      })
    })
  })

  return { periods, latest: Object.values(latestByKey) }
}
